title: <p align="center"> Abhishek Singh </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/abhishek-singh-frm-a30bb45/">LinkedIn</a> |
  <a href="https://github.com/abhisibm">GitHub</a>
  
  <br>   
  I'm working on regulatory compliance for multinational banks and financial institutions.
  Currently pursuing Masters in Data Science from UoA.
  <br>
  </p>



theme: jekyll-theme-minimal
